/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
-- find total customers by countries
select 
	country , 
	count(customer_id) as total_customers
from gold.dim_customers
group by 
	country;

-- find total customers by gender
select 
	gender , 
	count(customer_id) as total_customers
from gold.dim_customers
group by 
	gender

-- find total products by category
select 
	category , 
	count(product_key) as total_products
from gold.dim_products
group by category

-- average costs in each category
select 
	avg(cost) as average_cost_per_category , 
	category
from gold.dim_products
group by 
	category

-- total revenue generated for each category
select 
	category ,  
	sum(sales_amount) as total_revenue
from gold.fact_sales 
left join gold.dim_products 
	on gold.fact_sales.product_key = gold.dim_products.product_key
group by 
	category

-- find total revenue generated by each customer
select 
	gold.fact_sales.customer_key ,
	sum(sales_amount) as revenue_per_customer
from gold.fact_sales 
left join gold.dim_customers 
	on gold.fact_sales.customer_key = gold.dim_customers.customer_key 
group by 
	gold.fact_sales.customer_key
order by revenue_per_customer desc


-- distribution of sold items across countries
select 
country , sum(quantity) as total_products_per_country
from gold.dim_customers join gold.fact_sales
on gold.dim_customers.customer_key = gold.fact_sales.customer_key
group by country
